from pygame.examples.grid import WINDOW_WIDTH, WINDOW_HEIGHT

#c
COLOR_ORANGE = (255, 128, 0)
COLOR_WHITE = (255, 255, 255)


#M
#CRIA AS OPÇOES DO MENU NUMA DECLARAÇÃO CHAMADA MENU_OPTION
MENU_OPTION = ('NEW GAME 1P',
               'NEW GAME 2P - COOPERATIVE',
               'NEW GAME 2P - COMPETITIVE',
               'SCORE',
               'EXIT')

#w
#ESTABELECE DEFINIÇÕES DO TAMANHO DA JANELA (MESMA PROPORÇÃO DA IMAGEM DO MENU INICIAL.
WINDOW_WIDTH =526
WINDOW_HEIGHT =324
